### ISSUE TITLE
直接下载exe程序就能使用吗，我正常下载了，能打开，但是无法正常使用

### ISSUE THREAD

**Issue by LouisLin0903** [Frica01/WeChatMassTool#17]

**Comment by LouisLin0903** [comment]
![image](https://github.com/user-attachments/assets/144554dd-11b8-41f8-9e04-213290a1a6c8)

**Comment by Frica01** [comment]
![image](https://github.com/user-attachments/assets/4791efb3-c659-42d9-a554-aa40abbb0a72)


建议自行打包
实在不行就通过readme下方的联系方式获取
